project:
  type: website
  output-dir: docs

website:
  title: "Maddie Pickens"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - portfolio.qmd
    right:
      - icon: github
        href: https://github.com/mclaire19

format:
  html:
    #theme: cosmo
    css: styles.css

editor: visual

